### ISSUE TITLE
pandoc: input/roam/: openBinaryFile: inappropriate type (is a directory) (RuntimeError)

### ISSUE THREAD

**Issue by sabyabhoi** [goshatch/orgroam_to_obsidian#3]
I've followed all the steps given in the README, but open executing the convert.rb script, I get the following error:
```
/var/lib/gems/3.0.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:306:in `execute': pandoc: input/roam/: openBinaryFile: inappropriate type (is a directory) (RuntimeError)
	from /var/lib/gems/3.0.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:275:in `execute_pandoc'
	from /var/lib/gems/3.0.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:269:in `convert_string'
	from /var/lib/gems/3.0.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:205:in `convert'
	from /var/lib/gems/3.0.0/gems/pandoc-ruby-2.1.7/lib/pandoc-ruby.rb:241:in `block (2 levels) in <class:PandocRuby>'
	from ./convert.rb:38:in `input_file_to_md'
	from ./convert.rb:16:in `initialize'
	from ./convert.rb:60:in `new'
	from ./convert.rb:60:in `block in initialize'
	from ./convert.rb:59:in `each'
	from ./convert.rb:59:in `initialize'
	from ./convert.rb:95:in `new'
	from ./convert.rb:95:in `<main>'
```

**Comment by goshatch** [comment]
Hi @sabyabhoi, did you end up finding a solution to this? From the error you shared, it seems like a file Pandoc is trying to convert is a directory instead of a file.

**Comment by sabyabhoi** [comment]
Hey! I ended up manually converting my orgfiles (since I didn't have a lot of them). But I couldn't get the script to work.

**Comment by goshatch** [comment]
Thank you. I will close the issue for now, if someone else runs into this, please let me know and I will reopen it.

**Comment by mariuskreutzer** [comment]
I also had the same error. In my case, the problem was that the script expects all files to be inside a directory called "roam". You can fix this relatively easily by editing line 24 of the script.

In my case, the original path contained a `/Roam/`, and I placed all contents from `/Roam/` into input. I then changed the line to: `@input_file ||= "input/#{@row.file.partition('Roam/').last}"`
