### ISSUE TITLE
[Feature Request] Add support for subdirectories

### ISSUE THREAD

**Issue by CD11b** [goshatch/orgroam_to_obsidian#9]
I typically separate my .org files into different subdirectories. It would be helpful if the converter could take note of what sub-directory the /input .org file is located in and convert it to a file in an identically-named subdirectory in /output. A workaround could be adding the ability to skip conversion if the file is missing in /input but present in the DB.

**Comment by goshatch** [comment]
Hello! Thank you for the feature request. As I don't currently have much free time, I'd be happy to review a PR introducing this, if you (or anyone else) would like to take it up.
